services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "5050:3000"
    networks:
      - todo-app-network

  postgres:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: nestjs_db
      POSTGRES_USER: nestjs_user
      POSTGRES_PASSWORD: nestjs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_nodejs_data:/var/lib/postgresql/data
    networks:
      - todo-app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - webroot:/var/www/html
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - todo-app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email waleedez@gmail.com --agree-tos --no-eff-email --non-interactive --keep-until-expiring -d waleedez2.ddns.net

networks:
  todo-app-network:
    driver: bridge

volumes:
  postgres_nodejs_data:
  webroot:
  certbot-etc:
  certbot-var:
